init -2 python:
    gui.init(1920, 1080)

init -2 define gui.accent_color = "#a55758"
init -2 define gui.idle_color = "#FFFFFF"
init -2 define gui.idle_small_color = "#aaaaaa"
init -2 define gui.hover_color = "#0099cc"
init -2 define gui.selected_color = "#a55758"
init -2 define gui.insensitive_color = "#8888887f"
init -2 define gui.muted_color = "#00513d"
init -2 define gui.hover_muted_color = "#007a5b"
init -2 define gui.text_color = "#ffffff"
init -2 define gui.interface_text_color = "#ffffff"
init -2 define gui.text_font = "fonts/sm-main.ttf"
init -2 define gui.name_text_font = "fonts/sm-decorative.ttf"
init -2 define gui.interface_text_font = "fonts/sm-main.ttf"
init -2 define gui.text_size = 33
init -2 define gui.name_text_size = 45
init -2 define gui.interface_text_size = 33
init -2 define gui.label_text_size = 36
init -2 define gui.notify_text_size = 24
init -2 define gui.title_text_size = 75
init -2 define gui.main_menu_background = "gui/main_menu.png"
init -2 define gui.game_menu_background = "gui/game_menu.png"
init -2 define gui.textbox_height = 270
init -2 define gui.textbox_yalign = 1.0
init -2 define gui.name_xpos = 360
init -2 define gui.name_ypos = 0
init -2 define gui.name_xalign = 0.0
init -2 define gui.namebox_width = None
init -2 define gui.namebox_height = None
init -2 define gui.namebox_borders = Borders(5, 5, 5, 5)
init -2 define gui.namebox_tile = False
init -2 define gui.dialogue_xpos = 402
init -2 define gui.dialogue_ypos = 75
init -2 define gui.dialogue_width = 1116
init -2 define gui.dialogue_text_xalign = 0.0
init -2 define gui.button_width = None
init -2 define gui.button_height = None
init -2 define gui.button_borders = Borders(6, 6, 6, 6)
init -2 define gui.button_tile = False
init -2 define gui.button_text_font = gui.interface_text_font
init -2 define gui.button_text_size = gui.interface_text_size
init -2 define gui.button_text_idle_color = gui.idle_color
init -2 define gui.button_text_hover_color = gui.hover_color
init -2 define gui.button_text_selected_color = gui.selected_color
init -2 define gui.button_text_insensitive_color = gui.insensitive_color
init -2 define gui.button_text_xalign = 0.0
init -2 define gui.radio_button_borders = Borders(27, 6, 6, 6)
init -2 define gui.check_button_borders = Borders(27, 6, 6, 6)
init -2 define gui.confirm_button_text_xalign = 0.5
init -2 define gui.page_button_borders = Borders(15, 6, 15, 6)
init -2 define gui.quick_button_borders = Borders(15, 6, 15, 0)
init -2 define gui.quick_button_text_size = 21
init -2 define gui.quick_button_text_idle_color = gui.idle_small_color
init -2 define gui.quick_button_text_selected_color = gui.accent_color
init -2 define gui.choice_button_width = 1185
init -2 define gui.choice_button_height = None
init -2 define gui.choice_button_tile = False
init -2 define gui.choice_button_borders = Borders(150, 8, 150, 8)
init -2 define gui.choice_button_text_font = gui.text_font
init -2 define gui.choice_button_text_size = gui.text_size
init -2 define gui.choice_button_text_xalign = 0.5
init -2 define gui.choice_button_text_idle_color = "#cccccc"
init -2 define gui.choice_button_text_hover_color = "#ffffff"
init -2 define gui.choice_button_text_insensitive_color = "#444444"
init -2 define gui.slot_button_width = 414
init -2 define gui.slot_button_height = 309
init -2 define gui.slot_button_borders = Borders(15, 15, 15, 15)
init -2 define gui.slot_button_text_size = 21
init -2 define gui.slot_button_text_xalign = 0.5
init -2 define gui.slot_button_text_idle_color = gui.idle_small_color
init -2 define gui.slot_button_text_selected_idle_color = gui.selected_color
init -2 define gui.slot_button_text_selected_hover_color = gui.hover_color
init -2 define config.thumbnail_width = 384
init -2 define config.thumbnail_height = 216
init -2 define gui.file_slot_cols = 3
init -2 define gui.file_slot_rows = 2
init -2 define gui.navigation_xpos = 60
init -2 define gui.skip_ypos = 15
init -2 define gui.notify_ypos = 68
init -2 define gui.choice_spacing = 33
init -2 define gui.navigation_spacing = 6
init -2 define gui.pref_spacing = 15
init -2 define gui.pref_button_spacing = 0
init -2 define gui.page_spacing = 0
init -2 define gui.slot_spacing = 15
init -2 define gui.main_menu_text_xalign = 1.0
init -2 define gui.frame_borders = Borders(6, 6, 6, 6)
init -2 define gui.confirm_frame_borders = Borders(60, 60, 60, 60)
init -2 define gui.skip_frame_borders = Borders(24, 8, 75, 8)
init -2 define gui.notify_frame_borders = Borders(15, 10, 15, 10)
init -2 define gui.frame_tile = False
init -2 define gui.bar_size = 38
init -2 define gui.scrollbar_size = 18
init -2 define gui.slider_size = 38
init -2 define gui.bar_tile = False
init -2 define gui.scrollbar_tile = False
init -2 define gui.slider_tile = False
init -2 define gui.bar_borders = Borders(2, 2, 2, 2)
init -2 define gui.scrollbar_borders = Borders(6, 6, 6, 6)
init -2 define gui.slider_borders = Borders(6, 6, 6, 6)
init -2 define gui.vbar_borders = Borders(2, 2, 2, 2)
init -2 define gui.vscrollbar_borders = Borders(6, 6, 6, 6)
init -2 define gui.vslider_borders = Borders(6, 6, 6, 6)
init -2 define gui.unscrollable = "hide"
init -2 define config.history_length = 250
init -2 define gui.history_height = 210
init -2 define gui.history_name_xpos = 233
init -2 define gui.history_name_ypos = 0
init -2 define gui.history_name_width = 233
init -2 define gui.history_name_xalign = 1.0
init -2 define gui.history_text_xpos = 255
init -2 define gui.history_text_ypos = 3
init -2 define gui.history_text_width = 1110
init -2 define gui.history_text_xalign = 0.0
init -2 define gui.nvl_borders = Borders(0, 15, 0, 30)
init -2 define gui.nvl_list_length = 6
init -2 define gui.nvl_height = 173
init -2 define gui.nvl_spacing = 15
init -2 define gui.nvl_name_xpos = 645
init -2 define gui.nvl_name_ypos = 0
init -2 define gui.nvl_name_width = 225
init -2 define gui.nvl_name_xalign = 1.0
init -2 define gui.nvl_text_xpos = 675
init -2 define gui.nvl_text_ypos = 12
init -2 define gui.nvl_text_width = 885
init -2 define gui.nvl_text_xalign = 0.0
init -2 define gui.nvl_thought_xpos = 360
init -2 define gui.nvl_thought_ypos = 0
init -2 define gui.nvl_thought_width = 1170
init -2 define gui.nvl_thought_xalign = 0.0
init -2 define gui.nvl_button_xpos = 675
init -2 define gui.nvl_button_xalign = 0.0
init -2 define gui.language = "unicode"