#requires -Version 7.2
<#
.SYNOPSIS
Scans an original English Ren'Py game folder, imports only source-like files needed
for voice work, and opens a draft GitHub pull request for review.

Script name: Import-OriginalGameVoiceSource.ps1
Version: 202609.26
Author: Marco's Copilot

.DESCRIPTION
The script is intended to run on the Windows developer machine that contains the
original game files. It uses a Windows folder picker unless -GamePath is supplied.

It copies source-like text files from the selected game folder into
original-source/game while excluding Ren'Py translations, caches, saves, compiled
files, media, archives, and executables. It also creates a SHA-256 manifest and an
import report, creates a dedicated Git branch, commits the snapshot, pushes it, and
opens a draft pull request against the English voice branch.

No Gemini or other AI API calls are made by this script.

.PARAMETER GamePath
Path to the game installation root or directly to its game folder. Defaults to
E:\Games\Fetish Locator SM Studio. If the configured path is unavailable, a Windows
folder picker is shown.

.PARAMETER RepositoryPath
Path to the primary local clone of this repository. Defaults to X:\dev\repos\personal\FL-SM-1-translations-dutch. The script auto-detects the worktree that has the English voice branch checked out.

.PARAMETER BaseBranch
Git branch that receives the source-import pull request.

.PARAMETER BranchName
Optional explicit import branch. A timestamped branch name is generated by default.

.PARAMETER DestinationRelativePath
Repository-relative folder used for the imported source snapshot.

.PARAMETER SkipPush
Create the local branch and commit but do not push it.

.PARAMETER SkipPullRequest
Push the branch but do not create a draft pull request.

.PARAMETER AllowPotentialSecrets
Continue when the conservative secret-pattern scan finds a possible credential.
The scan never prints the suspected secret value.

.EXAMPLE
.\tools\Import-OriginalGameVoiceSource.ps1

.EXAMPLE
.\tools\Import-OriginalGameVoiceSource.ps1 -GamePath 'D:\Games\Fetish Locator S&M Studio'
#>

[CmdletBinding()]
param(
    [Parameter()]
    [string]$GamePath = 'E:\Games\Fetish Locator SM Studio',

    [Parameter()]
    [string]$RepositoryPath = 'X:\dev\repos\personal\FL-SM-1-translations-dutch',

    [Parameter()]
    [string]$BaseBranch = 'voice/english-gemini-tts',

    [Parameter()]
    [string]$BranchName,

    [Parameter()]
    [string]$DestinationRelativePath = 'original-source',

    [Parameter()]
    [switch]$SkipPush,

    [Parameter()]
    [switch]$SkipPullRequest,

    [Parameter()]
    [switch]$AllowPotentialSecrets,

    [Parameter()]
    [switch]$SelfTest
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$script:ScriptVersion = '202609.26'
$script:RepositoryRoot = $null
$script:TranscriptStarted = $false
$script:RpycdecVersion = '0.2.0'
$script:RpycdecWheelSha256 = '5354959b7881c67ed87bcbd29a954bf44df10defd200314379a4cad3b98a89ec'
$script:MinimumManifestCoverage = 0.95

$script:AllowedExtensions = @(
    '.rpy',
    '.rpym',
    '.py',
    '.json',
    '.yaml',
    '.yml',
    '.toml',
    '.ini',
    '.cfg',
    '.csv',
    '.tsv',
    '.txt'
)

$script:ExcludedTopLevelFolders = @(
    'tl',
    'saves',
    'cache',
    '__pycache__',
    '.vscode',
    'audio'
)

$script:CompiledExtensions = @(
    '.rpyc',
    '.rpymc'
)

$script:ArchiveExtractionSuffixes = @(
    '.rpy',
    '.rpym',
    '.rpyc',
    '.rpymc',
    '.py',
    '.json',
    '.yaml',
    '.yml',
    '.toml',
    '.ini',
    '.cfg',
    '.csv',
    '.tsv',
    '.txt'
)

$script:SecretPatterns = [ordered]@{
    'Private key block' = '-----BEGIN (?:RSA |EC |OPENSSH |DSA )?PRIVATE KEY-----'
    'GitHub classic token' = '\bgh[pousr]_[A-Za-z0-9]{20,}\b'
    'GitHub fine-grained token' = '\bgithub_pat_[A-Za-z0-9_]{20,}\b'
    'Google API key' = '\bAIza[0-9A-Za-z_-]{30,}\b'
    'OpenAI-style key' = '\bsk-[A-Za-z0-9_-]{20,}\b'
    'AWS access key' = '\bAKIA[0-9A-Z]{16}\b'
}

function Write-Status {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$Message,

        [Parameter()]
        [ValidateSet('Info', 'Success', 'Warning')]
        [string]$Level = 'Info'
    )

    $prefix = switch ($Level) {
        'Success' { '[OK]' }
        'Warning' { '[WARN]' }
        default { '[INFO]' }
    }

    Write-Host "$prefix $Message"
}

function Select-GameFolder {
    [CmdletBinding()]
    param()

    if (-not [System.OperatingSystem]::IsWindows()) {
        throw 'The folder picker requires Windows. Use -GamePath on non-Windows systems.'
    }

    $description = 'Select the game installation folder or its game folder.'

    try {
        Add-Type -AssemblyName System.Windows.Forms -ErrorAction Stop

        $dialog = [System.Windows.Forms.FolderBrowserDialog]::new()
        try {
            $dialog.Description = $description
            $dialog.ShowNewFolderButton = $false

            $result = $dialog.ShowDialog()
            if ($result -eq [System.Windows.Forms.DialogResult]::OK -and $dialog.SelectedPath) {
                return $dialog.SelectedPath
            }
        }
        finally {
            $dialog.Dispose()
        }
    }
    catch {
        Write-Status -Level Warning -Message "WinForms folder picker failed: $($_.Exception.Message)"
        Write-Status -Message 'Trying the Windows Shell folder picker instead.'

        $shell = New-Object -ComObject Shell.Application
        $folder = $shell.BrowseForFolder(0, $description, 0, 0)

        if ($null -ne $folder -and $null -ne $folder.Self.Path) {
            return [string]$folder.Self.Path
        }
    }

    throw 'Folder selection was cancelled.'
}

function Resolve-GameFolder {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$SelectedPath
    )

    $resolved = (Resolve-Path -LiteralPath $SelectedPath).Path
    $childGame = Join-Path $resolved 'game'

    if (Test-Path -LiteralPath $childGame -PathType Container) {
        $candidate = $childGame
    }
    elseif ((Split-Path -Leaf $resolved) -ieq 'game') {
        $candidate = $resolved
    }
    else {
        $candidate = $resolved
    }

    $hasRenPySource = Get-ChildItem -LiteralPath $candidate -Filter '*.rpy' -File -Recurse -ErrorAction SilentlyContinue |
        Where-Object {
            $relative = [System.IO.Path]::GetRelativePath($candidate, $_.FullName).Replace('\', '/')
            $parts = $relative -split '/'
            $parts.Count -eq 0 -or $parts[0] -ine 'tl'
        } |
        Select-Object -First 1

    if ($null -eq $hasRenPySource) {
        throw "No original Ren'Py .rpy source files were found under: $candidate"
    }

    return (Resolve-Path -LiteralPath $candidate).Path
}

function Invoke-Git {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string[]]$Arguments,

        [Parameter()]
        [switch]$Capture
    )

    $output = & git -C $script:RepositoryRoot @Arguments 2>&1
    $exitCode = $LASTEXITCODE

    if ($exitCode -ne 0) {
        $message = ($output | Out-String).Trim()
        throw "git $($Arguments -join ' ') failed with exit code $exitCode. $message"
    }

    if ($Capture) {
        return ($output | Out-String).Trim()
    }

    if ($output) {
        $output | ForEach-Object { Write-Host $_ }
    }
}

function Get-RepositorySlug {
    [CmdletBinding()]
    param()

    $remoteUrl = Invoke-Git -Arguments @('remote', 'get-url', 'origin') -Capture

    $patterns = @(
        '^https://github\.com/(?<slug>[^/]+/[^/]+?)(?:\.git)?$',
        '^git@github\.com:(?<slug>[^/]+/[^/]+?)(?:\.git)?$',
        '^ssh://git@github\.com/(?<slug>[^/]+/[^/]+?)(?:\.git)?$'
    )

    foreach ($pattern in $patterns) {
        if ($remoteUrl -match $pattern) {
            return $Matches.slug
        }
    }

    throw "Could not determine a GitHub owner/repository from origin: $remoteUrl"
}

function Test-Repository {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$Path
    )

    if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
        throw 'Git is not installed or not available in PATH.'
    }

    $resolvedPath = (Resolve-Path -LiteralPath $Path).Path
    $topLevel = (& git -C $resolvedPath rev-parse --show-toplevel 2>&1)
    if ($LASTEXITCODE -ne 0) {
        throw "RepositoryPath is not inside a Git repository: $resolvedPath"
    }

    $repositoryRoot = ($topLevel | Out-String).Trim()
    $script:RepositoryRoot = $repositoryRoot

    $origin = Invoke-Git -Arguments @('remote', 'get-url', 'origin') -Capture
    if (-not $origin) {
        throw 'The repository does not have an origin remote.'
    }

    return $repositoryRoot
}

function Get-BranchWorktree {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$RepositoryRoot,

        [Parameter(Mandatory)]
        [string]$BranchName
    )

    $output = & git -C $RepositoryRoot worktree list --porcelain 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "Unable to enumerate Git worktrees: $(($output | Out-String).Trim())"
    }

    $currentPath = $null
    $currentBranch = $null
    $matches = [System.Collections.Generic.List[string]]::new()

    foreach ($line in @($output) + '') {
        if ([string]::IsNullOrWhiteSpace($line)) {
            if ($currentPath -and $currentBranch -eq "refs/heads/$BranchName") {
                $matches.Add($currentPath)
            }

            $currentPath = $null
            $currentBranch = $null
            continue
        }

        if ($line -like 'worktree *') {
            $currentPath = $line.Substring(9)
            continue
        }

        if ($line -like 'branch *') {
            $currentBranch = $line.Substring(7)
        }
    }

    if ($matches.Count -gt 1) {
        throw "More than one worktree reports branch '$BranchName': $($matches -join ', ')"
    }

    if ($matches.Count -eq 1) {
        return (Resolve-Path -LiteralPath $matches[0]).Path
    }

    return $null
}

function Initialize-BranchWorktree {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$RepositoryRoot,

        [Parameter(Mandatory)]
        [string]$BranchName
    )

    $existing = Get-BranchWorktree -RepositoryRoot $RepositoryRoot -BranchName $BranchName
    if ($existing) {
        return $existing
    }

    $status = & git -C $RepositoryRoot status --porcelain 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "Unable to inspect repository status: $(($status | Out-String).Trim())"
    }

    if (-not ($status | Out-String).Trim()) {
        Write-Status -Message "No worktree currently has $BranchName checked out. Switching the clean primary clone to that branch."

        $switchOutput = & git -C $RepositoryRoot switch $BranchName 2>&1
        if ($LASTEXITCODE -ne 0) {
            $switchOutput = & git -C $RepositoryRoot switch --create $BranchName --track "origin/$BranchName" 2>&1
            if ($LASTEXITCODE -ne 0) {
                throw "Unable to switch the primary clone to ${BranchName}: $(($switchOutput | Out-String).Trim())"
            }
        }

        return $RepositoryRoot
    }

    $repositoryName = Split-Path -Leaf $RepositoryRoot
    $safeBranchName = $BranchName -replace '[^A-Za-z0-9._-]', '-'
    $worktreePath = Join-Path (Split-Path -Parent $RepositoryRoot) "$repositoryName-$safeBranchName"

    if (Test-Path -LiteralPath $worktreePath) {
        $candidateRoot = (& git -C $worktreePath rev-parse --show-toplevel 2>$null | Out-String).Trim()
        $candidateBranch = (& git -C $worktreePath branch --show-current 2>$null | Out-String).Trim()

        if ($LASTEXITCODE -eq 0 -and $candidateRoot -and $candidateBranch -eq $BranchName) {
            return $candidateRoot
        }

        throw "Cannot automatically create the voice worktree because the target path already exists: $worktreePath"
    }

    Write-Status -Level Warning -Message 'The primary clone has uncommitted work, so it will not be switched.'
    Write-Status -Message "Creating a dedicated worktree for $BranchName at $worktreePath."

    $localBranchExists = $false
    & git -C $RepositoryRoot show-ref --verify --quiet "refs/heads/$BranchName"
    if ($LASTEXITCODE -eq 0) {
        $localBranchExists = $true
    }

    if ($localBranchExists) {
        $worktreeOutput = & git -C $RepositoryRoot worktree add $worktreePath $BranchName 2>&1
    }
    else {
        $worktreeOutput = & git -C $RepositoryRoot worktree add -b $BranchName $worktreePath "origin/$BranchName" 2>&1
    }

    if ($LASTEXITCODE -ne 0) {
        throw "Unable to create the voice worktree: $(($worktreeOutput | Out-String).Trim())"
    }

    return (Resolve-Path -LiteralPath $worktreePath).Path
}


function ConvertTo-GameRelativePath {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$RelativePath
    )

    $normalized = $RelativePath.Replace('\', '/').TrimStart('/')
    if ($normalized -like 'game/*') {
        $normalized = $normalized.Substring(5)
    }

    return $normalized
}

function Test-ExcludedSourcePath {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$RelativePath
    )

    $normalized = ConvertTo-GameRelativePath -RelativePath $RelativePath
    $segments = @($normalized -split '/')
    if ($segments.Count -eq 0) {
        return $false
    }

    return $script:ExcludedTopLevelFolders -icontains $segments[0]
}

function Get-PackagedSourceInventory {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$GameRoot
    )

    $archives = [System.Collections.Generic.List[object]]::new()
    $compiled = [System.Collections.Generic.List[object]]::new()

    foreach ($file in Get-ChildItem -LiteralPath $GameRoot -File -Recurse -Force) {
        $relativePath = ConvertTo-GameRelativePath -RelativePath ([System.IO.Path]::GetRelativePath($GameRoot, $file.FullName))
        $extension = $file.Extension.ToLowerInvariant()

        if ($extension -eq '.rpa') {
            $archives.Add([pscustomobject]@{
                FullName = $file.FullName
                RelativePath = $relativePath
                Length = [int64]$file.Length
            })
            continue
        }

        if ($script:CompiledExtensions -icontains $extension) {
            if (-not (Test-ExcludedSourcePath -RelativePath $relativePath)) {
                $compiled.Add([pscustomobject]@{
                    FullName = $file.FullName
                    RelativePath = $relativePath
                    Extension = $extension
                    Length = [int64]$file.Length
                })
            }
        }
    }

    return [pscustomobject]@{
        Archives = @($archives)
        CompiledScripts = @($compiled)
    }
}

function Get-PythonLauncher {
    [CmdletBinding()]
    param()

    $candidates = @(
        [pscustomobject]@{ Command = 'py'; Prefix = @('-3') },
        [pscustomobject]@{ Command = 'python'; Prefix = @() },
        [pscustomobject]@{ Command = 'python3'; Prefix = @() }
    )

    foreach ($candidate in $candidates) {
        if (-not (Get-Command $candidate.Command -ErrorAction SilentlyContinue)) {
            continue
        }

        & $candidate.Command @($candidate.Prefix) -c 'import sys; raise SystemExit(0 if sys.version_info >= (3, 10) else 1)' *> $null
        if ($LASTEXITCODE -eq 0) {
            return $candidate
        }
    }

    throw 'Python 3.10 or newer is required to reconstruct Ren''Py archives/compiled scripts. Install Python 3.10+ and ensure py, python, or python3 is available in PATH.'
}

function New-RpycdecEnvironment {
    [CmdletBinding()]
    param()

    $launcher = Get-PythonLauncher
    $environmentRoot = Join-Path ([System.IO.Path]::GetTempPath()) "rpycdec-$([guid]::NewGuid().ToString('N'))"

    Write-Status -Message "Creating isolated rpycdec $($script:RpycdecVersion) environment."

    $venvOutput = & $launcher.Command @($launcher.Prefix) -m venv $environmentRoot 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "Unable to create the temporary Python environment: $(($venvOutput | Out-String).Trim())"
    }

    $pythonPath = if ([System.OperatingSystem]::IsWindows()) {
        Join-Path $environmentRoot 'Scripts\python.exe'
    }
    else {
        Join-Path $environmentRoot 'bin/python'
    }

    if (-not (Test-Path -LiteralPath $pythonPath -PathType Leaf)) {
        throw "Temporary Python interpreter was not created: $pythonPath"
    }

    $requirementsPath = Join-Path $environmentRoot 'rpycdec-requirements.txt'
    "rpycdec==$($script:RpycdecVersion) --hash=sha256:$($script:RpycdecWheelSha256)" | Set-Content -LiteralPath $requirementsPath -Encoding ascii

    $pipArguments = @(
        '-m', 'pip', 'install',
        '--disable-pip-version-check',
        '--no-deps',
        '--require-hashes',
        '--requirement', $requirementsPath
    )
    $pipOutput = & $pythonPath @pipArguments 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "Unable to install pinned rpycdec $($script:RpycdecVersion): $(($pipOutput | Out-String).Trim())"
    }

    $versionOutput = & $pythonPath -c 'import importlib.metadata; print(importlib.metadata.version("rpycdec"))' 2>&1
    if ($LASTEXITCODE -ne 0 -or (($versionOutput | Out-String).Trim() -ne $script:RpycdecVersion)) {
        throw "Pinned rpycdec version verification failed: $(($versionOutput | Out-String).Trim())"
    }

    Write-Status -Level Success -Message "Pinned rpycdec $($script:RpycdecVersion) is ready."

    return [pscustomobject]@{
        Root = $environmentRoot
        Python = $pythonPath
        Version = $script:RpycdecVersion
    }
}

function Invoke-Rpycdec {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$PythonPath,

        [Parameter(Mandatory)]
        [string[]]$Arguments
    )

    $previousWarningSetting = $env:RPYCDEC_NO_WARNING
    try {
        $env:RPYCDEC_NO_WARNING = '1'
        $output = & $PythonPath -m rpycdec @Arguments 2>&1
        $exitCode = $LASTEXITCODE
    }
    finally {
        if ($null -eq $previousWarningSetting) {
            Remove-Item Env:RPYCDEC_NO_WARNING -ErrorAction SilentlyContinue
        }
        else {
            $env:RPYCDEC_NO_WARNING = $previousWarningSetting
        }
    }

    if ($exitCode -ne 0) {
        throw "rpycdec $($Arguments -join ' ') failed with exit code $exitCode. $(($output | Out-String).Trim())"
    }

    if ($output) {
        $output | ForEach-Object { Write-Host $_ }
    }
}

function Copy-TreeFiles {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$SourceRoot,

        [Parameter(Mandatory)]
        [string]$DestinationRoot,

        [Parameter()]
        [switch]$IncludeCompiled,

        [Parameter()]
        [switch]$Overwrite,

        [Parameter()]
        [System.Collections.Generic.List[string]]$Conflicts
    )

    foreach ($file in Get-ChildItem -LiteralPath $SourceRoot -File -Recurse -Force) {
        $relativePath = ConvertTo-GameRelativePath -RelativePath ([System.IO.Path]::GetRelativePath($SourceRoot, $file.FullName))

        if (Test-ExcludedSourcePath -RelativePath $relativePath) {
            continue
        }

        $extension = $file.Extension.ToLowerInvariant()
        $allowed = $script:AllowedExtensions -icontains $extension
        if ($IncludeCompiled) {
            $allowed = $allowed -or ($script:CompiledExtensions -icontains $extension)
        }

        if (-not $allowed) {
            continue
        }

        $platformRelative = $relativePath.Replace('/', [System.IO.Path]::DirectorySeparatorChar)
        $target = Join-Path $DestinationRoot $platformRelative
        $targetParent = Split-Path -Parent $target

        if (-not (Test-Path -LiteralPath $targetParent)) {
            New-Item -ItemType Directory -Path $targetParent -Force | Out-Null
        }

        if (Test-Path -LiteralPath $target -PathType Leaf) {
            $sourceHash = (Get-FileHash -LiteralPath $file.FullName -Algorithm SHA256).Hash
            $targetHash = (Get-FileHash -LiteralPath $target -Algorithm SHA256).Hash

            if ($sourceHash -eq $targetHash) {
                continue
            }

            if (-not $Overwrite) {
                if ($Conflicts) {
                    $Conflicts.Add($relativePath)
                }
                continue
            }
        }

        Copy-Item -LiteralPath $file.FullName -Destination $target -Force
    }
}

function New-MaterializedGameSource {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$GameRoot
    )

    $inventory = Get-PackagedSourceInventory -GameRoot $GameRoot
    $archiveCount = @($inventory.Archives).Count
    $looseCompiledCount = @($inventory.CompiledScripts).Count

    if ($archiveCount -eq 0 -and $looseCompiledCount -eq 0) {
        return [pscustomobject]@{
            SourceRoot = $GameRoot
            ReconstructionUsed = $false
            WorkspaceRoot = $null
            ToolEnvironmentRoot = $null
            RpycdecVersion = $null
            ArchiveCount = 0
            ArchiveFiles = @()
            LooseCompiledCount = 0
            DecompiledScriptCount = 0
            ArchiveConflicts = @()
        }
    }

    Write-Status -Message "Packaged Ren'Py source detected: $archiveCount RPA archive(s), $looseCompiledCount loose compiled script(s)."

    $toolEnvironment = New-RpycdecEnvironment
    $workspaceRoot = Join-Path ([System.IO.Path]::GetTempPath()) "renpy-source-$([guid]::NewGuid().ToString('N'))"
    $rawRoot = Join-Path $workspaceRoot 'raw'
    $decompiledRoot = Join-Path $workspaceRoot 'decompiled'
    $materializedRoot = Join-Path $workspaceRoot 'materialized'
    $archiveRoot = Join-Path $workspaceRoot 'archives'

    foreach ($path in @($rawRoot, $decompiledRoot, $materializedRoot, $archiveRoot)) {
        New-Item -ItemType Directory -Path $path -Force | Out-Null
    }

    $conflicts = [System.Collections.Generic.List[string]]::new()
    $archiveMetadata = [System.Collections.Generic.List[object]]::new()
    $archives = @($inventory.Archives | Sort-Object RelativePath -Descending)

    for ($index = 0; $index -lt $archives.Count; $index++) {
        $archive = $archives[$index]
        $archiveOutput = Join-Path $archiveRoot ("{0:D3}-{1}" -f $index, ([System.IO.Path]::GetFileNameWithoutExtension($archive.FullName)))
        New-Item -ItemType Directory -Path $archiveOutput -Force | Out-Null

        Write-Status -Message "Extracting script/data candidates from archive: $($archive.RelativePath)"

        $arguments = @('unrpa', $archive.FullName, '-o', $archiveOutput, '-s') + $script:ArchiveExtractionSuffixes
        Invoke-Rpycdec -PythonPath $toolEnvironment.Python -Arguments $arguments

        Copy-TreeFiles -SourceRoot $archiveOutput -DestinationRoot $rawRoot -IncludeCompiled -Conflicts $conflicts

        $archiveMetadata.Add([ordered]@{
            path = $archive.RelativePath
            size_bytes = $archive.Length
            sha256 = (Get-FileHash -LiteralPath $archive.FullName -Algorithm SHA256).Hash.ToLowerInvariant()
        })
    }

    # Loose game files are copied last and intentionally override archive entries.
    Copy-TreeFiles -SourceRoot $GameRoot -DestinationRoot $rawRoot -IncludeCompiled -Overwrite

    $compiledInRaw = @(
        Get-ChildItem -LiteralPath $rawRoot -File -Recurse -Force |
            Where-Object { $script:CompiledExtensions -icontains $_.Extension.ToLowerInvariant() }
    )

    if ($compiledInRaw.Count -gt 0) {
        Write-Status -Message "Decompiling $($compiledInRaw.Count) effective Ren'Py compiled script(s)."
        Invoke-Rpycdec -PythonPath $toolEnvironment.Python -Arguments @('decompile', $rawRoot, '-o', $decompiledRoot)
    }

    $directScan = Get-SourceScan -GameRoot $rawRoot
    foreach ($file in $directScan.SelectedFiles) {
        $platformRelative = $file.RelativePath.Replace('/', [System.IO.Path]::DirectorySeparatorChar)
        $target = Join-Path $materializedRoot $platformRelative
        $targetParent = Split-Path -Parent $target
        if (-not (Test-Path -LiteralPath $targetParent)) {
            New-Item -ItemType Directory -Path $targetParent -Force | Out-Null
        }
        Copy-Item -LiteralPath $file.FullName -Destination $target -Force
    }

    $decompiledScripts = @(
        Get-ChildItem -LiteralPath $decompiledRoot -Filter '*.rpy' -File -Recurse -Force
    )

    foreach ($file in $decompiledScripts) {
        $relativePath = ConvertTo-GameRelativePath -RelativePath ([System.IO.Path]::GetRelativePath($decompiledRoot, $file.FullName))

        if (Test-ExcludedSourcePath -RelativePath $relativePath) {
            continue
        }

        $platformRelative = $relativePath.Replace('/', [System.IO.Path]::DirectorySeparatorChar)
        $target = Join-Path $materializedRoot $platformRelative
        if (Test-Path -LiteralPath $target -PathType Leaf) {
            continue
        }

        $targetParent = Split-Path -Parent $target
        if (-not (Test-Path -LiteralPath $targetParent)) {
            New-Item -ItemType Directory -Path $targetParent -Force | Out-Null
        }

        Copy-Item -LiteralPath $file.FullName -Destination $target -Force
    }

    return [pscustomobject]@{
        SourceRoot = $materializedRoot
        ReconstructionUsed = $true
        WorkspaceRoot = $workspaceRoot
        ToolEnvironmentRoot = $toolEnvironment.Root
        RpycdecVersion = $toolEnvironment.Version
        ArchiveCount = $archiveCount
        ArchiveFiles = @($archiveMetadata)
        LooseCompiledCount = $looseCompiledCount
        DecompiledScriptCount = @($decompiledScripts).Count
        ArchiveConflicts = @($conflicts | Sort-Object -Unique)
    }
}

function Get-ManifestCoverage {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$SourceRoot,

        [Parameter(Mandatory)]
        [string]$ManifestPath
    )

    if (-not (Test-Path -LiteralPath $ManifestPath -PathType Leaf)) {
        throw "Expected source inventory is missing: $ManifestPath"
    }

    $expectedRows = @(Import-Csv -LiteralPath $ManifestPath)
    if ($expectedRows.Count -eq 0) {
        throw "Expected source inventory is empty: $ManifestPath"
    }

    $available = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)

    foreach ($file in Get-ChildItem -LiteralPath $SourceRoot -Filter '*.rpy' -File -Recurse -Force) {
        $relativePath = ConvertTo-GameRelativePath -RelativePath ([System.IO.Path]::GetRelativePath($SourceRoot, $file.FullName))
        [void]$available.Add($relativePath)
    }

    $missing = [System.Collections.Generic.List[string]]::new()
    $covered = 0

    foreach ($row in $expectedRows) {
        $expectedPath = ConvertTo-GameRelativePath -RelativePath ([string]$row.relative_path)
        if ($available.Contains($expectedPath)) {
            $covered++
        }
        else {
            $missing.Add($expectedPath)
        }
    }

    $coverage = [double]$covered / [double]$expectedRows.Count

    return [pscustomobject]@{
        ExpectedCount = $expectedRows.Count
        CoveredCount = $covered
        MissingCount = $missing.Count
        Coverage = $coverage
        MissingPaths = @($missing)
    }
}

function Get-SourceScan {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$GameRoot
    )

    $selected = [System.Collections.Generic.List[object]]::new()
    $total = 0
    $excludedTranslations = 0
    $excludedUnsupported = 0

    foreach ($file in Get-ChildItem -LiteralPath $GameRoot -File -Recurse -Force) {
        $total++
        $relativePath = ConvertTo-GameRelativePath -RelativePath ([System.IO.Path]::GetRelativePath($GameRoot, $file.FullName))
        $segments = @($relativePath -split '/')

        if (Test-ExcludedSourcePath -RelativePath $relativePath) {
            if ($segments.Count -gt 0 -and $segments[0] -ieq 'tl') {
                $excludedTranslations++
            }
            continue
        }

        if ($script:AllowedExtensions -inotcontains $file.Extension) {
            $excludedUnsupported++
            continue
        }

        $selected.Add([pscustomobject]@{
            FullName = $file.FullName
            RelativePath = $relativePath
            Extension = $file.Extension.ToLowerInvariant()
            Length = [int64]$file.Length
        })
    }

    return [pscustomobject]@{
        TotalFiles = $total
        SelectedFiles = @($selected)
        ExcludedTranslations = $excludedTranslations
        ExcludedUnsupported = $excludedUnsupported
    }
}

function Find-PotentialSecret {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [object[]]$Files
    )

    $hits = [System.Collections.Generic.List[object]]::new()

    foreach ($file in $Files) {
        try {
            $content = Get-Content -LiteralPath $file.FullName -Raw -ErrorAction Stop
        }
        catch {
            Write-Status -Level Warning -Message "Could not scan text content in $($file.RelativePath): $($_.Exception.Message)"
            continue
        }

        foreach ($entry in $script:SecretPatterns.GetEnumerator()) {
            if ($content -match $entry.Value) {
                $hits.Add([pscustomobject]@{
                    RelativePath = $file.RelativePath
                    Pattern = $entry.Key
                })
            }
        }
    }

    return @($hits)
}

function Get-SafeDestination {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$RelativePath
    )

    if ([System.IO.Path]::IsPathRooted($RelativePath) -or [string]::IsNullOrWhiteSpace($RelativePath)) {
        throw 'DestinationRelativePath must be a non-empty repository-relative path.'
    }

    $root = [System.IO.Path]::GetFullPath($script:RepositoryRoot)
    $destination = [System.IO.Path]::GetFullPath((Join-Path $root $RelativePath))
    $rootPrefix = $root.TrimEnd('\', '/') + [System.IO.Path]::DirectorySeparatorChar

    if (-not $destination.StartsWith($rootPrefix, [System.StringComparison]::OrdinalIgnoreCase)) {
        throw 'DestinationRelativePath resolves outside the repository.'
    }

    if ($destination -eq (Join-Path $root '.git')) {
        throw 'DestinationRelativePath cannot target .git.'
    }

    return $destination
}

function Copy-SourceSnapshot {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$GameRoot,

        [Parameter(Mandatory)]
        [object[]]$Files,

        [Parameter(Mandatory)]
        [string]$DestinationRoot,

        [Parameter(Mandatory)]
        [string]$RepositorySlug,

        [Parameter(Mandatory)]
        [string]$ImportBranch,

        [Parameter(Mandatory)]
        [object]$ReconstructionInfo,

        [Parameter(Mandatory)]
        [object]$CoverageInfo
    )

    if (Test-Path -LiteralPath $DestinationRoot) {
        Remove-Item -LiteralPath $DestinationRoot -Recurse -Force
    }

    $destinationGame = Join-Path $DestinationRoot 'game'
    New-Item -ItemType Directory -Path $destinationGame -Force | Out-Null

    $manifestFiles = [System.Collections.Generic.List[object]]::new()
    $copiedBytes = [int64]0

    foreach ($file in $Files) {
        $platformRelative = $file.RelativePath.Replace('/', [System.IO.Path]::DirectorySeparatorChar)
        $target = Join-Path $destinationGame $platformRelative
        $targetParent = Split-Path -Parent $target

        if (-not (Test-Path -LiteralPath $targetParent)) {
            New-Item -ItemType Directory -Path $targetParent -Force | Out-Null
        }

        Copy-Item -LiteralPath $file.FullName -Destination $target -Force
        $hash = (Get-FileHash -LiteralPath $file.FullName -Algorithm SHA256).Hash.ToLowerInvariant()
        $copiedBytes += $file.Length

        $manifestFiles.Add([ordered]@{
            path = "game/$($file.RelativePath)"
            extension = $file.Extension
            size_bytes = $file.Length
            source_sha256 = $hash
        })
    }

    $manifest = [ordered]@{
        schema_version = 1
        import_tool = 'Import-OriginalGameVoiceSource.ps1'
        import_tool_version = $script:ScriptVersion
        imported_at_utc = (Get-Date).ToUniversalTime().ToString('o')
        source_kind = 'original_english_renpy_game_source'
        source_folder_name = (Split-Path -Leaf $GameRoot)
        repository = $RepositorySlug
        base_branch = $BaseBranch
        import_branch = $ImportBranch
        file_count = $manifestFiles.Count
        total_bytes = $copiedBytes
        reconstruction = [ordered]@{
            used = [bool]$ReconstructionInfo.ReconstructionUsed
            tool = if ($ReconstructionInfo.ReconstructionUsed) { 'rpycdec' } else { $null }
            tool_version = $ReconstructionInfo.RpycdecVersion
            archive_count = [int]$ReconstructionInfo.ArchiveCount
            loose_compiled_count = [int]$ReconstructionInfo.LooseCompiledCount
            decompiled_script_count = [int]$ReconstructionInfo.DecompiledScriptCount
            archive_conflict_count = @($ReconstructionInfo.ArchiveConflicts).Count
            archives = @($ReconstructionInfo.ArchiveFiles)
        }
        expected_source_coverage = [ordered]@{
            expected_paths = [int]$CoverageInfo.ExpectedCount
            covered_paths = [int]$CoverageInfo.CoveredCount
            missing_paths = [int]$CoverageInfo.MissingCount
            coverage_ratio = [math]::Round([double]$CoverageInfo.Coverage, 6)
        }
        excluded = [ordered]@{
            translations = 'game/tl/**'
            compiled = '*.rpyc, *.pyc'
            media_and_archives = 'not selected by source-extension allowlist'
            saves_and_cache = 'game/saves/**, game/cache/**'
        }
        files = @($manifestFiles)
    }

    $manifestPath = Join-Path $DestinationRoot 'SOURCE_MANIFEST.json'
    $manifest | ConvertTo-Json -Depth 10 |
        Set-Content -LiteralPath $manifestPath -Encoding utf8NoBOM

    $coveragePath = Join-Path $DestinationRoot 'SOURCE_COVERAGE.json'
    [ordered]@{
        expected_count = [int]$CoverageInfo.ExpectedCount
        covered_count = [int]$CoverageInfo.CoveredCount
        missing_count = [int]$CoverageInfo.MissingCount
        coverage_ratio = [math]::Round([double]$CoverageInfo.Coverage, 6)
        missing_paths = @($CoverageInfo.MissingPaths)
    } | ConvertTo-Json -Depth 6 |
        Set-Content -LiteralPath $coveragePath -Encoding utf8NoBOM

    $byExtension = $Files |
        Group-Object Extension |
        Sort-Object Name |
        ForEach-Object { "| $($_.Name) | $($_.Count) |" }

    $reportLines = @(
        '# Original English game source import',
        '',
        "Imported at UTC: $($manifest.imported_at_utc)",
        "Importer version: $($script:ScriptVersion)",
        "Source folder label: $($manifest.source_folder_name)",
        "Repository: $RepositorySlug",
        "Base branch: $BaseBranch",
        "Import branch: $ImportBranch",
        '',
        '## Scope',
        '',
        'This snapshot contains original English Ren''Py source-like text files needed to reconstruct dialogue, speaker bindings, variables, character definitions, labels, and related voice integration context.',
        '',
        'The importer deliberately excludes translation folders, compiled Ren''Py/Python files, saves, caches, media, archives, and executables.',
        '',
        'No AI/TTS requests are made by the importer.',
        '',
        '## File counts',
        '',
        '| Extension | Files |',
        '| --- | ---: |'
    ) + $byExtension + @(
        '',
        "Total imported files: $($manifest.file_count)",
        "Total imported bytes: $($manifest.total_bytes)",
        '',
        '## Reconstruction',
        '',
        "RPA archives processed: $($manifest.reconstruction.archive_count)",
        "Loose compiled scripts found: $($manifest.reconstruction.loose_compiled_count)",
        "Compiled scripts decompiled: $($manifest.reconstruction.decompiled_script_count)",
        "Archive path conflicts resolved by archive priority: $($manifest.reconstruction.archive_conflict_count)",
        "Reconstruction tool: $(if ($manifest.reconstruction.used) { "rpycdec $($manifest.reconstruction.tool_version)" } else { 'not required' })",
        '',
        '## Expected source coverage',
        '',
        "Expected .rpy paths from project inventory: $($CoverageInfo.ExpectedCount)",
        "Covered paths: $($CoverageInfo.CoveredCount)",
        "Missing paths: $($CoverageInfo.MissingCount)",
        ("Coverage: {0:P2}" -f [double]$CoverageInfo.Coverage),
        '',
        'See SOURCE_COVERAGE.json for the exact missing-path review list.',
        '',
        '## Review',
        '',
        'Review this draft pull request before merging. SOURCE_MANIFEST.json records the original SHA-256 hash and size for every imported file.',
        '',
        'After merge, the English voice extractor can be changed to treat original-source/game as the canonical dialogue and character source.'
    )

    $reportPath = Join-Path $DestinationRoot 'IMPORT_REPORT.md'
    $reportLines | Set-Content -LiteralPath $reportPath -Encoding utf8NoBOM

    return [pscustomobject]@{
        ManifestPath = $manifestPath
        CoveragePath = $coveragePath
        ReportPath = $reportPath
        FileCount = $manifest.file_count
        TotalBytes = $manifest.total_bytes
    }
}

function New-DraftPullRequest {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$RepositorySlug,

        [Parameter(Mandatory)]
        [string]$ImportBranch,

        [Parameter(Mandatory)]
        [int]$FileCount,

        [Parameter(Mandatory)]
        [int64]$TotalBytes,

        [Parameter(Mandatory)]
        [object]$ReconstructionInfo,

        [Parameter(Mandatory)]
        [object]$CoverageInfo
    )

    if (-not (Get-Command gh -ErrorAction SilentlyContinue)) {
        throw 'GitHub CLI (gh) is required to create the pull request. Install it with: winget install --id GitHub.cli --exact'
    }

    & gh auth status --hostname github.com 2>&1 | ForEach-Object { Write-Host $_ }
    if ($LASTEXITCODE -ne 0) {
        throw 'GitHub CLI is not authenticated. Run: gh auth login'
    }

    $bodyPath = Join-Path ([System.IO.Path]::GetTempPath()) "voice-source-import-pr-$([guid]::NewGuid().ToString('N')).md"

    try {
        @(
            '## Original English game source snapshot',
            '',
            "Imported source files: $FileCount",
            "Imported bytes: $TotalBytes",
            "Expected source coverage: $($CoverageInfo.CoveredCount)/$($CoverageInfo.ExpectedCount) ($('{0:P2}' -f [double]$CoverageInfo.Coverage))",
            "RPA archives processed: $($ReconstructionInfo.ArchiveCount)",
            "Compiled scripts decompiled: $($ReconstructionInfo.DecompiledScriptCount)",
            '',
            '### Purpose',
            '',
            'Make the original English Ren''Py source available to the English voice pipeline so dialogue, speakers, variables, character definitions, and scene context can be reviewed directly instead of reconstructed from translation exports.',
            '',
            '### Safety / scope',
            '',
            '- Draft PR only. Do not merge before review.',
            '- game/tl translations are excluded.',
            '- RPA archives and compiled Ren''Py scripts are reconstructed in a temporary workspace; binary archives/compiled files are not committed.',
            '- saves, cache, media, archives, compiled files and executables are excluded from the PR.',
            '- SOURCE_MANIFEST.json records SHA-256 hashes, reconstruction provenance and coverage.',
            '- SOURCE_COVERAGE.json lists any expected .rpy paths still missing.',
            '- No Gemini/TTS calls were made by the import script.',
            '',
            '### Review target',
            '',
            'After source review, update the voice extractor to use original-source/game as the canonical English source.'
        ) | Set-Content -LiteralPath $bodyPath -Encoding utf8NoBOM

        $title = 'voice: import original English RenPy source snapshot'
        $ghArguments = @(
            'pr', 'create',
            '--repo', $RepositorySlug,
            '--base', $BaseBranch,
            '--head', $ImportBranch,
            '--title', $title,
            '--body-file', $bodyPath,
            '--draft'
        )

        $output = & gh @ghArguments 2>&1

        if ($LASTEXITCODE -ne 0) {
            throw "gh pr create failed: $(($output | Out-String).Trim())"
        }

        return ($output | Select-Object -Last 1).ToString().Trim()
    }
    finally {
        Remove-Item -LiteralPath $bodyPath -Force -ErrorAction SilentlyContinue
    }
}

function Invoke-ImporterSelfTest {
    [CmdletBinding()]
    param()

    $testRoot = Join-Path ([System.IO.Path]::GetTempPath()) "voice-importer-selftest-$([guid]::NewGuid().ToString('N'))"

    try {
        New-Item -ItemType Directory -Path $testRoot -Force | Out-Null
        New-Item -ItemType Directory -Path (Join-Path $testRoot 'tl\dutch') -Force | Out-Null

        $safeFile = Join-Path $testRoot 'script.rpy'
        'define mc = Character("MC")' | Set-Content -LiteralPath $safeFile -Encoding utf8NoBOM

        $translatedFile = Join-Path $testRoot 'tl\dutch\script.rpy'
        'translate dutch test:' | Set-Content -LiteralPath $translatedFile -Encoding utf8NoBOM

        $compiledFile = Join-Path $testRoot 'script.rpyc'
        [System.IO.File]::WriteAllBytes($compiledFile, [byte[]](1, 2, 3, 4))

        $scan = Get-SourceScan -GameRoot $testRoot
        if ($scan.SelectedFiles.Count -ne 1) {
            throw "Self-test expected exactly one selected source file, got $($scan.SelectedFiles.Count)."
        }

        if ($scan.ExcludedTranslations -ne 1) {
            throw "Self-test expected one excluded translation file, got $($scan.ExcludedTranslations)."
        }

        $safeHits = @(Find-PotentialSecret -Files $scan.SelectedFiles)
        if ($safeHits.Count -ne 0) {
            throw "Self-test expected zero secret hits, got $($safeHits.Count)."
        }

        $secretFile = Join-Path $testRoot 'secret.txt'
        'AIza12345678901234567890123456789012345' | Set-Content -LiteralPath $secretFile -Encoding utf8NoBOM
        $secretInfo = Get-Item -LiteralPath $secretFile
        $secretCandidate = [pscustomobject]@{
            FullName = $secretInfo.FullName
            RelativePath = 'secret.txt'
            Extension = '.txt'
            Length = [int64]$secretInfo.Length
        }

        $secretHits = @(Find-PotentialSecret -Files @($secretCandidate))
        if ($secretHits.Count -ne 1) {
            throw "Self-test expected one secret hit, got $($secretHits.Count)."
        }

        Write-Status -Level Success -Message 'Importer runtime self-test passed.'
    }
    finally {
        Remove-Item -LiteralPath $testRoot -Recurse -Force -ErrorAction SilentlyContinue
    }
}

if ($SelfTest) {
    Invoke-ImporterSelfTest
    exit 0
}

$timestamp = Get-Date -Format 'yyyyMMdd-HHmmss'
$logPath = Join-Path ([System.IO.Path]::GetTempPath()) "Import-OriginalGameVoiceSource-$timestamp.log"
$voiceWorktreeRoot = $null
$importWorktreePath = $null
$removeImportWorktree = $false

try {
    Start-Transcript -Path $logPath -Force | Out-Null
    $script:TranscriptStarted = $true

    Write-Status -Message "Log: $logPath"

    $primaryRepositoryRoot = Test-Repository -Path $RepositoryPath
    Write-Status -Message "Primary repository: $primaryRepositoryRoot"

    Write-Status -Message "Fetching origin before resolving the voice worktree."
    Invoke-Git -Arguments @('fetch', 'origin', '--prune')
    [void](Invoke-Git -Arguments @('rev-parse', '--verify', "origin/$BaseBranch") -Capture)

    $voiceWorktreeRoot = Initialize-BranchWorktree -RepositoryRoot $primaryRepositoryRoot -BranchName $BaseBranch
    $script:RepositoryRoot = $voiceWorktreeRoot

    $activeBranch = Invoke-Git -Arguments @('branch', '--show-current') -Capture
    if ($activeBranch -ne $BaseBranch) {
        throw "Resolved worktree is on '$activeBranch' instead of '$BaseBranch': $voiceWorktreeRoot"
    }

    $dirty = Invoke-Git -Arguments @('status', '--porcelain') -Capture
    if ($dirty) {
        throw "The voice worktree has uncommitted changes. Commit or stash them first: $voiceWorktreeRoot"
    }

    Write-Status -Message "Voice worktree: $voiceWorktreeRoot"
    Write-Status -Message "Voice branch: $BaseBranch"
    Invoke-Git -Arguments @('pull', '--ff-only', 'origin', $BaseBranch)

    if (-not $GamePath -or -not (Test-Path -LiteralPath $GamePath -PathType Container)) {
        if ($GamePath) {
            Write-Status -Level Warning -Message "Configured game path was not found: $GamePath"
        }

        $GamePath = Select-GameFolder
    }

    $gameRoot = Resolve-GameFolder -SelectedPath $GamePath
    Write-Status -Message "Game source root: $gameRoot"

    $scan = Get-SourceScan -GameRoot $gameRoot
    if ($scan.SelectedFiles.Count -eq 0) {
        throw 'No source-like files matched the import allowlist.'
    }

    Write-Status -Message "Files scanned: $($scan.TotalFiles)"
    Write-Status -Message "Source files selected: $($scan.SelectedFiles.Count)"
    Write-Status -Message "Translation files excluded: $($scan.ExcludedTranslations)"
    Write-Status -Message "Unsupported/binary files excluded: $($scan.ExcludedUnsupported)"

    $secretHits = @(Find-PotentialSecret -Files $scan.SelectedFiles)
    if ($secretHits.Count -gt 0) {
        foreach ($hit in $secretHits) {
            Write-Status -Level Warning -Message "Potential secret pattern '$($hit.Pattern)' in $($hit.RelativePath)"
        }

        if (-not $AllowPotentialSecrets) {
            throw 'Potential credentials were detected. Review the files first, then rerun with -AllowPotentialSecrets only if the findings are false positives.'
        }
    }

    if (-not $BranchName) {
        $BranchName = "voice/import-original-source-$timestamp"
    }

    & git -C $script:RepositoryRoot show-ref --verify --quiet "refs/heads/$BranchName"
    if ($LASTEXITCODE -eq 0) {
        throw "Local branch already exists: $BranchName"
    }

    & git -C $script:RepositoryRoot ls-remote --exit-code --heads origin $BranchName *> $null
    if ($LASTEXITCODE -eq 0) {
        throw "Remote branch already exists: $BranchName"
    }

    $repositorySlug = Get-RepositorySlug
    Write-Status -Message "GitHub repository: $repositorySlug"

    $safeRepositoryName = ($repositorySlug -split '/')[1] -replace '[^A-Za-z0-9._-]', '-'
    $importWorktreePath = Join-Path ([System.IO.Path]::GetTempPath()) "$safeRepositoryName-source-import-$timestamp"

    if (Test-Path -LiteralPath $importWorktreePath) {
        throw "Temporary import worktree path already exists: $importWorktreePath"
    }

    Write-Status -Message "Creating temporary PR worktree for $BranchName."
    $worktreeOutput = & git -C $voiceWorktreeRoot worktree add -b $BranchName $importWorktreePath "origin/$BaseBranch" 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "Unable to create import worktree: $(($worktreeOutput | Out-String).Trim())"
    }

    $script:RepositoryRoot = $importWorktreePath
    Write-Status -Message "Temporary import worktree: $importWorktreePath"

    $destinationRoot = Get-SafeDestination -RelativePath $DestinationRelativePath
    $copyParameters = @{
        GameRoot = $gameRoot
        Files = $scan.SelectedFiles
        DestinationRoot = $destinationRoot
        RepositorySlug = $repositorySlug
        ImportBranch = $BranchName
    }
    $copyResult = Copy-SourceSnapshot @copyParameters

    Write-Status -Message "Imported $($copyResult.FileCount) files into $DestinationRelativePath/game."

    Invoke-Git -Arguments @('add', '--', $DestinationRelativePath)

    $status = Invoke-Git -Arguments @('status', '--short') -Capture
    if (-not $status) {
        throw 'The import produced no Git changes.'
    }

    Write-Host $status

    Invoke-Git -Arguments @(
        'commit',
        '-m',
        'chore(voice): import original English RenPy source snapshot'
    )

    if ($SkipPush) {
        Write-Status -Level Warning -Message 'Push skipped. No pull request was created.'
        Write-Status -Level Success -Message "Local import branch ready: $BranchName"
        Write-Status -Message "Import worktree retained for inspection: $importWorktreePath"
        return
    }

    Write-Status -Message "Pushing $BranchName."
    Invoke-Git -Arguments @('push', '--set-upstream', 'origin', $BranchName)

    if ($SkipPullRequest) {
        Write-Status -Level Warning -Message 'Draft pull request creation skipped.'
        Write-Status -Level Success -Message "Remote import branch ready: $BranchName"
        $removeImportWorktree = $true
        return
    }

    $pullRequestParameters = @{
        RepositorySlug = $repositorySlug
        ImportBranch = $BranchName
        FileCount = $copyResult.FileCount
        TotalBytes = $copyResult.TotalBytes
    }
    $pullRequestUrl = New-DraftPullRequest @pullRequestParameters

    Write-Status -Level Success -Message "Draft pull request created: $pullRequestUrl"
    Write-Status -Message 'Leave the PR unmerged so the imported English source can be reviewed first.'
    $removeImportWorktree = $true
}
catch {
    Write-Status -Level Warning -Message $_.Exception.Message
    Write-Status -Message "See the transcript for details: $logPath"
    throw
}
finally {
    if ($removeImportWorktree -and $voiceWorktreeRoot -and $importWorktreePath -and (Test-Path -LiteralPath $importWorktreePath)) {
        try {
            $script:RepositoryRoot = $voiceWorktreeRoot
            $removeOutput = & git -C $voiceWorktreeRoot worktree remove --force $importWorktreePath 2>&1
            if ($LASTEXITCODE -ne 0) {
                Write-Status -Level Warning -Message "Could not remove temporary import worktree: $(($removeOutput | Out-String).Trim())"
            }
            else {
                Write-Status -Message "Removed temporary import worktree: $importWorktreePath"
            }
        }
        catch {
            Write-Status -Level Warning -Message "Could not clean up temporary import worktree: $($_.Exception.Message)"
        }
    }
    elseif ($importWorktreePath -and (Test-Path -LiteralPath $importWorktreePath)) {
        Write-Status -Message "Import worktree retained: $importWorktreePath"
    }

    if ($script:TranscriptStarted) {
        Stop-Transcript | Out-Null
    }
}
