#requires -Version 7.2
<#
.SYNOPSIS
Scans an original English Ren'Py game folder, imports only source-like files needed
for voice work, and opens a draft GitHub pull request for review.

Script name: Import-OriginalGameVoiceSource.ps1
Version: 202609.25
Author: Marco's Copilot

.DESCRIPTION
The script is intended to run on the Windows developer machine that contains the
original game files. It uses a Windows folder picker unless -GamePath is supplied.

It copies source-like text files from the selected game folder into
original-source/game while excluding Ren'Py translations, caches, saves, compiled
files, media, archives, and executables. It also creates a SHA-256 manifest and an
import report, creates a dedicated Git branch, commits the snapshot, pushes it, and
opens a draft pull request against the English voice branch.

No Gemini or other AI API calls are made by this script.

.PARAMETER GamePath
Optional path to the game installation root or directly to its game folder. When
omitted, a Windows folder picker is shown.

.PARAMETER RepositoryPath
Path to the primary local clone of this repository. Defaults to X:\dev\personal\FL-SM-1-translations-dutch. The script auto-detects the worktree that has the English voice branch checked out.

.PARAMETER BaseBranch
Git branch that receives the source-import pull request.

.PARAMETER BranchName
Optional explicit import branch. A timestamped branch name is generated by default.

.PARAMETER DestinationRelativePath
Repository-relative folder used for the imported source snapshot.

.PARAMETER SkipPush
Create the local branch and commit but do not push it.

.PARAMETER SkipPullRequest
Push the branch but do not create a draft pull request.

.PARAMETER AllowPotentialSecrets
Continue when the conservative secret-pattern scan finds a possible credential.
The scan never prints the suspected secret value.

.EXAMPLE
.\tools\Import-OriginalGameVoiceSource.ps1

.EXAMPLE
.\tools\Import-OriginalGameVoiceSource.ps1 -GamePath 'D:\Games\Fetish Locator S&M Studio'
#>

[CmdletBinding()]
param(
    [Parameter()]
    [string]$GamePath,

    [Parameter()]
    [string]$RepositoryPath = 'X:\dev\personal\FL-SM-1-translations-dutch',

    [Parameter()]
    [string]$BaseBranch = 'voice/english-gemini-tts',

    [Parameter()]
    [string]$BranchName,

    [Parameter()]
    [string]$DestinationRelativePath = 'original-source',

    [Parameter()]
    [switch]$SkipPush,

    [Parameter()]
    [switch]$SkipPullRequest,

    [Parameter()]
    [switch]$AllowPotentialSecrets
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$script:ScriptVersion = '202609.25'
$script:RepositoryRoot = $null
$script:TranscriptStarted = $false

$script:AllowedExtensions = @(
    '.rpy',
    '.rpym',
    '.py',
    '.json',
    '.yaml',
    '.yml',
    '.toml',
    '.ini',
    '.cfg',
    '.csv',
    '.tsv',
    '.txt'
)

$script:ExcludedTopLevelFolders = @(
    'tl',
    'saves',
    'cache',
    '__pycache__'
)

$script:SecretPatterns = [ordered]@{
    'Private key block' = '-----BEGIN (?:RSA |EC |OPENSSH |DSA )?PRIVATE KEY-----'
    'GitHub classic token' = '\bgh[pousr]_[A-Za-z0-9]{20,}\b'
    'GitHub fine-grained token' = '\bgithub_pat_[A-Za-z0-9_]{20,}\b'
    'Google API key' = '\bAIza[0-9A-Za-z_-]{30,}\b'
    'OpenAI-style key' = '\bsk-[A-Za-z0-9_-]{20,}\b'
    'AWS access key' = '\bAKIA[0-9A-Z]{16}\b'
}

function Write-Status {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$Message,

        [Parameter()]
        [ValidateSet('Info', 'Success', 'Warning')]
        [string]$Level = 'Info'
    )

    $prefix = switch ($Level) {
        'Success' { '[OK]' }
        'Warning' { '[WARN]' }
        default { '[INFO]' }
    }

    Write-Host "$prefix $Message"
}

function Select-GameFolder {
    [CmdletBinding()]
    param()

    if (-not [System.OperatingSystem]::IsWindows()) {
        throw 'The folder picker requires Windows. Use -GamePath on non-Windows systems.'
    }

    $description = 'Select the game installation folder or its game folder.'

    try {
        Add-Type -AssemblyName System.Windows.Forms -ErrorAction Stop

        $dialog = [System.Windows.Forms.FolderBrowserDialog]::new()
        try {
            $dialog.Description = $description
            $dialog.ShowNewFolderButton = $false

            $result = $dialog.ShowDialog()
            if ($result -eq [System.Windows.Forms.DialogResult]::OK -and $dialog.SelectedPath) {
                return $dialog.SelectedPath
            }
        }
        finally {
            $dialog.Dispose()
        }
    }
    catch {
        Write-Status -Level Warning -Message "WinForms folder picker failed: $($_.Exception.Message)"
        Write-Status -Message 'Trying the Windows Shell folder picker instead.'

        $shell = New-Object -ComObject Shell.Application
        $folder = $shell.BrowseForFolder(0, $description, 0, 0)

        if ($null -ne $folder -and $null -ne $folder.Self.Path) {
            return [string]$folder.Self.Path
        }
    }

    throw 'Folder selection was cancelled.'
}

function Resolve-GameFolder {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$SelectedPath
    )

    $resolved = (Resolve-Path -LiteralPath $SelectedPath).Path
    $childGame = Join-Path $resolved 'game'

    if (Test-Path -LiteralPath $childGame -PathType Container) {
        $candidate = $childGame
    }
    elseif ((Split-Path -Leaf $resolved) -ieq 'game') {
        $candidate = $resolved
    }
    else {
        $candidate = $resolved
    }

    $hasRenPySource = Get-ChildItem -LiteralPath $candidate -Filter '*.rpy' -File -Recurse -ErrorAction SilentlyContinue |
        Where-Object {
            $relative = [System.IO.Path]::GetRelativePath($candidate, $_.FullName).Replace('\', '/')
            $parts = $relative -split '/'
            $parts.Count -eq 0 -or $parts[0] -ine 'tl'
        } |
        Select-Object -First 1

    if ($null -eq $hasRenPySource) {
        throw "No original Ren'Py .rpy source files were found under: $candidate"
    }

    return (Resolve-Path -LiteralPath $candidate).Path
}

function Invoke-Git {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string[]]$Arguments,

        [Parameter()]
        [switch]$Capture
    )

    $output = & git -C $script:RepositoryRoot @Arguments 2>&1
    $exitCode = $LASTEXITCODE

    if ($exitCode -ne 0) {
        $message = ($output | Out-String).Trim()
        throw "git $($Arguments -join ' ') failed with exit code $exitCode. $message"
    }

    if ($Capture) {
        return ($output | Out-String).Trim()
    }

    if ($output) {
        $output | ForEach-Object { Write-Host $_ }
    }
}

function Get-RepositorySlug {
    [CmdletBinding()]
    param()

    $remoteUrl = Invoke-Git -Arguments @('remote', 'get-url', 'origin') -Capture

    $patterns = @(
        '^https://github\.com/(?<slug>[^/]+/[^/]+?)(?:\.git)?$',
        '^git@github\.com:(?<slug>[^/]+/[^/]+?)(?:\.git)?$',
        '^ssh://git@github\.com/(?<slug>[^/]+/[^/]+?)(?:\.git)?$'
    )

    foreach ($pattern in $patterns) {
        if ($remoteUrl -match $pattern) {
            return $Matches.slug
        }
    }

    throw "Could not determine a GitHub owner/repository from origin: $remoteUrl"
}

function Test-Repository {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$Path
    )

    if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
        throw 'Git is not installed or not available in PATH.'
    }

    $resolvedPath = (Resolve-Path -LiteralPath $Path).Path
    $topLevel = (& git -C $resolvedPath rev-parse --show-toplevel 2>&1)
    if ($LASTEXITCODE -ne 0) {
        throw "RepositoryPath is not inside a Git repository: $resolvedPath"
    }

    $repositoryRoot = ($topLevel | Out-String).Trim()
    $script:RepositoryRoot = $repositoryRoot

    $origin = Invoke-Git -Arguments @('remote', 'get-url', 'origin') -Capture
    if (-not $origin) {
        throw 'The repository does not have an origin remote.'
    }

    return $repositoryRoot
}

function Get-BranchWorktree {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$RepositoryRoot,

        [Parameter(Mandatory)]
        [string]$BranchName
    )

    $output = & git -C $RepositoryRoot worktree list --porcelain 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "Unable to enumerate Git worktrees: $(($output | Out-String).Trim())"
    }

    $currentPath = $null
    $currentBranch = $null
    $matches = [System.Collections.Generic.List[string]]::new()

    foreach ($line in @($output) + '') {
        if ([string]::IsNullOrWhiteSpace($line)) {
            if ($currentPath -and $currentBranch -eq "refs/heads/$BranchName") {
                $matches.Add($currentPath)
            }

            $currentPath = $null
            $currentBranch = $null
            continue
        }

        if ($line -like 'worktree *') {
            $currentPath = $line.Substring(9)
            continue
        }

        if ($line -like 'branch *') {
            $currentBranch = $line.Substring(7)
        }
    }

    if ($matches.Count -gt 1) {
        throw "More than one worktree reports branch '$BranchName': $($matches -join ', ')"
    }

    if ($matches.Count -eq 1) {
        return (Resolve-Path -LiteralPath $matches[0]).Path
    }

    $currentBranchName = (& git -C $RepositoryRoot branch --show-current 2>&1 | Out-String).Trim()
    if ($LASTEXITCODE -eq 0 -and $currentBranchName -eq $BranchName) {
        return $RepositoryRoot
    }

    throw @"
No Git worktree has '$BranchName' checked out.

Create or switch a worktree for the voice branch first. The primary clone remains:
$RepositoryRoot

Example:
  git -C "$RepositoryRoot" fetch origin
  git -C "$RepositoryRoot" switch $BranchName
"@
}

function Get-SourceScan {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$GameRoot
    )

    $selected = [System.Collections.Generic.List[object]]::new()
    $total = 0
    $excludedTranslations = 0
    $excludedUnsupported = 0

    foreach ($file in Get-ChildItem -LiteralPath $GameRoot -File -Recurse -Force) {
        $total++
        $relativePath = [System.IO.Path]::GetRelativePath($GameRoot, $file.FullName).Replace('\', '/')
        $segments = $relativePath -split '/'

        if ($segments.Count -gt 0 -and $script:ExcludedTopLevelFolders -icontains $segments[0]) {
            if ($segments[0] -ieq 'tl') {
                $excludedTranslations++
            }
            continue
        }

        if ($script:AllowedExtensions -inotcontains $file.Extension) {
            $excludedUnsupported++
            continue
        }

        $selected.Add([pscustomobject]@{
            FullName = $file.FullName
            RelativePath = $relativePath
            Extension = $file.Extension.ToLowerInvariant()
            Length = [int64]$file.Length
        })
    }

    return [pscustomobject]@{
        TotalFiles = $total
        SelectedFiles = @($selected)
        ExcludedTranslations = $excludedTranslations
        ExcludedUnsupported = $excludedUnsupported
    }
}

function Find-PotentialSecret {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [object[]]$Files
    )

    $hits = [System.Collections.Generic.List[object]]::new()

    foreach ($file in $Files) {
        try {
            $content = Get-Content -LiteralPath $file.FullName -Raw -ErrorAction Stop
        }
        catch {
            Write-Status -Level Warning -Message "Could not scan text content in $($file.RelativePath): $($_.Exception.Message)"
            continue
        }

        foreach ($entry in $script:SecretPatterns.GetEnumerator()) {
            if ($content -match $entry.Value) {
                $hits.Add([pscustomobject]@{
                    RelativePath = $file.RelativePath
                    Pattern = $entry.Key
                })
            }
        }
    }

    return @($hits)
}

function Get-SafeDestination {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$RelativePath
    )

    if ([System.IO.Path]::IsPathRooted($RelativePath) -or [string]::IsNullOrWhiteSpace($RelativePath)) {
        throw 'DestinationRelativePath must be a non-empty repository-relative path.'
    }

    $root = [System.IO.Path]::GetFullPath($script:RepositoryRoot)
    $destination = [System.IO.Path]::GetFullPath((Join-Path $root $RelativePath))
    $rootPrefix = $root.TrimEnd('\', '/') + [System.IO.Path]::DirectorySeparatorChar

    if (-not $destination.StartsWith($rootPrefix, [System.StringComparison]::OrdinalIgnoreCase)) {
        throw 'DestinationRelativePath resolves outside the repository.'
    }

    if ($destination -eq (Join-Path $root '.git')) {
        throw 'DestinationRelativePath cannot target .git.'
    }

    return $destination
}

function Copy-SourceSnapshot {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$GameRoot,

        [Parameter(Mandatory)]
        [object[]]$Files,

        [Parameter(Mandatory)]
        [string]$DestinationRoot,

        [Parameter(Mandatory)]
        [string]$RepositorySlug,

        [Parameter(Mandatory)]
        [string]$ImportBranch
    )

    if (Test-Path -LiteralPath $DestinationRoot) {
        Remove-Item -LiteralPath $DestinationRoot -Recurse -Force
    }

    $destinationGame = Join-Path $DestinationRoot 'game'
    New-Item -ItemType Directory -Path $destinationGame -Force | Out-Null

    $manifestFiles = [System.Collections.Generic.List[object]]::new()
    $copiedBytes = [int64]0

    foreach ($file in $Files) {
        $platformRelative = $file.RelativePath.Replace('/', [System.IO.Path]::DirectorySeparatorChar)
        $target = Join-Path $destinationGame $platformRelative
        $targetParent = Split-Path -Parent $target

        if (-not (Test-Path -LiteralPath $targetParent)) {
            New-Item -ItemType Directory -Path $targetParent -Force | Out-Null
        }

        Copy-Item -LiteralPath $file.FullName -Destination $target -Force
        $hash = (Get-FileHash -LiteralPath $file.FullName -Algorithm SHA256).Hash.ToLowerInvariant()
        $copiedBytes += $file.Length

        $manifestFiles.Add([ordered]@{
            path = "game/$($file.RelativePath)"
            extension = $file.Extension
            size_bytes = $file.Length
            source_sha256 = $hash
        })
    }

    $manifest = [ordered]@{
        schema_version = 1
        import_tool = 'Import-OriginalGameVoiceSource.ps1'
        import_tool_version = $script:ScriptVersion
        imported_at_utc = (Get-Date).ToUniversalTime().ToString('o')
        source_kind = 'original_english_renpy_game_source'
        source_folder_name = (Split-Path -Leaf $GameRoot)
        repository = $RepositorySlug
        base_branch = $BaseBranch
        import_branch = $ImportBranch
        file_count = $manifestFiles.Count
        total_bytes = $copiedBytes
        excluded = [ordered]@{
            translations = 'game/tl/**'
            compiled = '*.rpyc, *.pyc'
            media_and_archives = 'not selected by source-extension allowlist'
            saves_and_cache = 'game/saves/**, game/cache/**'
        }
        files = @($manifestFiles)
    }

    $manifestPath = Join-Path $DestinationRoot 'SOURCE_MANIFEST.json'
    $manifest | ConvertTo-Json -Depth 8 |
        Set-Content -LiteralPath $manifestPath -Encoding utf8NoBOM

    $byExtension = $Files |
        Group-Object Extension |
        Sort-Object Name |
        ForEach-Object { "| $($_.Name) | $($_.Count) |" }

    $reportLines = @(
        '# Original English game source import',
        '',
        "Imported at UTC: $($manifest.imported_at_utc)",
        "Importer version: $($script:ScriptVersion)",
        "Source folder label: $($manifest.source_folder_name)",
        "Repository: $RepositorySlug",
        "Base branch: $BaseBranch",
        "Import branch: $ImportBranch",
        '',
        '## Scope',
        '',
        'This snapshot contains original English Ren''Py source-like text files needed to reconstruct dialogue, speaker bindings, variables, character definitions, labels, and related voice integration context.',
        '',
        'The importer deliberately excludes translation folders, compiled Ren''Py/Python files, saves, caches, media, archives, and executables.',
        '',
        'No AI/TTS requests are made by the importer.',
        '',
        '## File counts',
        '',
        '| Extension | Files |',
        '| --- | ---: |'
    ) + $byExtension + @(
        '',
        "Total imported files: $($manifest.file_count)",
        "Total imported bytes: $($manifest.total_bytes)",
        '',
        '## Review',
        '',
        'Review this draft pull request before merging. SOURCE_MANIFEST.json records the original SHA-256 hash and size for every imported file.',
        '',
        'After merge, the English voice extractor can be changed to treat original-source/game as the canonical dialogue and character source.'
    )

    $reportPath = Join-Path $DestinationRoot 'IMPORT_REPORT.md'
    $reportLines | Set-Content -LiteralPath $reportPath -Encoding utf8NoBOM

    return [pscustomobject]@{
        ManifestPath = $manifestPath
        ReportPath = $reportPath
        FileCount = $manifest.file_count
        TotalBytes = $manifest.total_bytes
    }
}

function New-DraftPullRequest {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$RepositorySlug,

        [Parameter(Mandatory)]
        [string]$ImportBranch,

        [Parameter(Mandatory)]
        [int]$FileCount,

        [Parameter(Mandatory)]
        [int64]$TotalBytes
    )

    if (-not (Get-Command gh -ErrorAction SilentlyContinue)) {
        throw 'GitHub CLI (gh) is required to create the pull request. Install it with: winget install --id GitHub.cli --exact'
    }

    & gh auth status --hostname github.com 2>&1 | ForEach-Object { Write-Host $_ }
    if ($LASTEXITCODE -ne 0) {
        throw 'GitHub CLI is not authenticated. Run: gh auth login'
    }

    $bodyPath = Join-Path $env:TEMP "voice-source-import-pr-$([guid]::NewGuid().ToString('N')).md"

    try {
        @(
            '## Original English game source snapshot',
            '',
            "Imported source files: $FileCount",
            "Imported bytes: $TotalBytes",
            '',
            '### Purpose',
            '',
            'Make the original English Ren''Py source available to the English voice pipeline so dialogue, speakers, variables, character definitions, and scene context can be reviewed directly instead of reconstructed from translation exports.',
            '',
            '### Safety / scope',
            '',
            '- Draft PR only. Do not merge before review.',
            '- game/tl translations are excluded.',
            '- compiled files, saves, cache, media, archives, and executables are excluded.',
            '- SOURCE_MANIFEST.json contains SHA-256 hashes for every imported source file.',
            '- No Gemini/TTS calls were made by the import script.',
            '',
            '### Review target',
            '',
            'After source review, update the voice extractor to use original-source/game as the canonical English source.'
        ) | Set-Content -LiteralPath $bodyPath -Encoding utf8NoBOM

        $title = 'voice: import original English RenPy source snapshot'
        $ghArguments = @(
            'pr', 'create',
            '--repo', $RepositorySlug,
            '--base', $BaseBranch,
            '--head', $ImportBranch,
            '--title', $title,
            '--body-file', $bodyPath,
            '--draft'
        )

        $output = & gh @ghArguments 2>&1

        if ($LASTEXITCODE -ne 0) {
            throw "gh pr create failed: $(($output | Out-String).Trim())"
        }

        return ($output | Select-Object -Last 1).ToString().Trim()
    }
    finally {
        Remove-Item -LiteralPath $bodyPath -Force -ErrorAction SilentlyContinue
    }
}

$timestamp = Get-Date -Format 'yyyyMMdd-HHmmss'
$logPath = Join-Path $env:TEMP "Import-OriginalGameVoiceSource-$timestamp.log"
$voiceWorktreeRoot = $null
$importWorktreePath = $null
$removeImportWorktree = $false

try {
    Start-Transcript -Path $logPath -Force | Out-Null
    $script:TranscriptStarted = $true

    Write-Status -Message "Log: $logPath"

    $primaryRepositoryRoot = Test-Repository -Path $RepositoryPath
    Write-Status -Message "Primary repository: $primaryRepositoryRoot"

    Write-Status -Message "Fetching origin before resolving the voice worktree."
    Invoke-Git -Arguments @('fetch', 'origin', '--prune')
    [void](Invoke-Git -Arguments @('rev-parse', '--verify', "origin/$BaseBranch") -Capture)

    $voiceWorktreeRoot = Get-BranchWorktree -RepositoryRoot $primaryRepositoryRoot -BranchName $BaseBranch
    $script:RepositoryRoot = $voiceWorktreeRoot

    $activeBranch = Invoke-Git -Arguments @('branch', '--show-current') -Capture
    if ($activeBranch -ne $BaseBranch) {
        throw "Resolved worktree is on '$activeBranch' instead of '$BaseBranch': $voiceWorktreeRoot"
    }

    $dirty = Invoke-Git -Arguments @('status', '--porcelain') -Capture
    if ($dirty) {
        throw "The voice worktree has uncommitted changes. Commit or stash them first: $voiceWorktreeRoot"
    }

    Write-Status -Message "Voice worktree: $voiceWorktreeRoot"
    Write-Status -Message "Voice branch: $BaseBranch"
    Invoke-Git -Arguments @('pull', '--ff-only', 'origin', $BaseBranch)

    if (-not $GamePath) {
        $GamePath = Select-GameFolder
    }

    $gameRoot = Resolve-GameFolder -SelectedPath $GamePath
    Write-Status -Message "Game source root: $gameRoot"

    $scan = Get-SourceScan -GameRoot $gameRoot
    if ($scan.SelectedFiles.Count -eq 0) {
        throw 'No source-like files matched the import allowlist.'
    }

    Write-Status -Message "Files scanned: $($scan.TotalFiles)"
    Write-Status -Message "Source files selected: $($scan.SelectedFiles.Count)"
    Write-Status -Message "Translation files excluded: $($scan.ExcludedTranslations)"
    Write-Status -Message "Unsupported/binary files excluded: $($scan.ExcludedUnsupported)"

    $secretHits = Find-PotentialSecret -Files $scan.SelectedFiles
    if ($secretHits.Count -gt 0) {
        foreach ($hit in $secretHits) {
            Write-Status -Level Warning -Message "Potential secret pattern '$($hit.Pattern)' in $($hit.RelativePath)"
        }

        if (-not $AllowPotentialSecrets) {
            throw 'Potential credentials were detected. Review the files first, then rerun with -AllowPotentialSecrets only if the findings are false positives.'
        }
    }

    if (-not $BranchName) {
        $BranchName = "voice/import-original-source-$timestamp"
    }

    & git -C $script:RepositoryRoot show-ref --verify --quiet "refs/heads/$BranchName"
    if ($LASTEXITCODE -eq 0) {
        throw "Local branch already exists: $BranchName"
    }

    & git -C $script:RepositoryRoot ls-remote --exit-code --heads origin $BranchName *> $null
    if ($LASTEXITCODE -eq 0) {
        throw "Remote branch already exists: $BranchName"
    }

    $repositorySlug = Get-RepositorySlug
    Write-Status -Message "GitHub repository: $repositorySlug"

    $safeRepositoryName = ($repositorySlug -split '/')[1] -replace '[^A-Za-z0-9._-]', '-'
    $importWorktreePath = Join-Path $env:TEMP "$safeRepositoryName-source-import-$timestamp"

    if (Test-Path -LiteralPath $importWorktreePath) {
        throw "Temporary import worktree path already exists: $importWorktreePath"
    }

    Write-Status -Message "Creating temporary PR worktree for $BranchName."
    $worktreeOutput = & git -C $voiceWorktreeRoot worktree add -b $BranchName $importWorktreePath "origin/$BaseBranch" 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "Unable to create import worktree: $(($worktreeOutput | Out-String).Trim())"
    }

    $script:RepositoryRoot = $importWorktreePath
    Write-Status -Message "Temporary import worktree: $importWorktreePath"

    $destinationRoot = Get-SafeDestination -RelativePath $DestinationRelativePath
    $copyParameters = @{
        GameRoot = $gameRoot
        Files = $scan.SelectedFiles
        DestinationRoot = $destinationRoot
        RepositorySlug = $repositorySlug
        ImportBranch = $BranchName
    }
    $copyResult = Copy-SourceSnapshot @copyParameters

    Write-Status -Message "Imported $($copyResult.FileCount) files into $DestinationRelativePath/game."

    Invoke-Git -Arguments @('add', '--', $DestinationRelativePath)

    $status = Invoke-Git -Arguments @('status', '--short') -Capture
    if (-not $status) {
        throw 'The import produced no Git changes.'
    }

    Write-Host $status

    Invoke-Git -Arguments @(
        'commit',
        '-m',
        'chore(voice): import original English RenPy source snapshot'
    )

    if ($SkipPush) {
        Write-Status -Level Warning -Message 'Push skipped. No pull request was created.'
        Write-Status -Level Success -Message "Local import branch ready: $BranchName"
        Write-Status -Message "Import worktree retained for inspection: $importWorktreePath"
        return
    }

    Write-Status -Message "Pushing $BranchName."
    Invoke-Git -Arguments @('push', '--set-upstream', 'origin', $BranchName)

    if ($SkipPullRequest) {
        Write-Status -Level Warning -Message 'Draft pull request creation skipped.'
        Write-Status -Level Success -Message "Remote import branch ready: $BranchName"
        $removeImportWorktree = $true
        return
    }

    $pullRequestParameters = @{
        RepositorySlug = $repositorySlug
        ImportBranch = $BranchName
        FileCount = $copyResult.FileCount
        TotalBytes = $copyResult.TotalBytes
    }
    $pullRequestUrl = New-DraftPullRequest @pullRequestParameters

    Write-Status -Level Success -Message "Draft pull request created: $pullRequestUrl"
    Write-Status -Message 'Leave the PR unmerged so the imported English source can be reviewed first.'
    $removeImportWorktree = $true
}
catch {
    Write-Status -Level Warning -Message $_.Exception.Message
    Write-Status -Message "See the transcript for details: $logPath"
    throw
}
finally {
    if ($removeImportWorktree -and $voiceWorktreeRoot -and $importWorktreePath -and (Test-Path -LiteralPath $importWorktreePath)) {
        try {
            $script:RepositoryRoot = $voiceWorktreeRoot
            $removeOutput = & git -C $voiceWorktreeRoot worktree remove --force $importWorktreePath 2>&1
            if ($LASTEXITCODE -ne 0) {
                Write-Status -Level Warning -Message "Could not remove temporary import worktree: $(($removeOutput | Out-String).Trim())"
            }
            else {
                Write-Status -Message "Removed temporary import worktree: $importWorktreePath"
            }
        }
        catch {
            Write-Status -Level Warning -Message "Could not clean up temporary import worktree: $($_.Exception.Message)"
        }
    }
    elseif ($importWorktreePath -and (Test-Path -LiteralPath $importWorktreePath)) {
        Write-Status -Message "Import worktree retained: $importWorktreePath"
    }

    if ($script:TranscriptStarted) {
        Stop-Transcript | Out-Null
    }
}
